[workspace]
members = ["parser-sqllog", "dm-database-parser"]
resolver = "3"

[workspace.dependencies]
# 日志相关依赖
tracing = { version = "0.1.41" }
tracing-subscriber = { version = "0.3.20", features = ["env-filter"] }
tracing-appender = { version = "0.2.3" }
