[sqllog]
thread_num = 0   # 线程数量
batch_size = 0   # 每次处理的行数
path = "sqllogs" # 绝对路径与相对路径均可

[logging]
level = "debug" # 日志级别，可选值：trace, debug, info, warn, error
path = "logs"   # 日志文件路径

[error_exporter]
path = "output/error.log" # 错误日志输出路径
overwrite = true          # 是否覆盖已存在的文件
append = false            # 是否以追加的方式写入文件
