[sqllog]
thread_num = 4    # 线程数量
batch_size = 1000 # 每次处理的行数
path = "sqllog"   # 绝对路径与相对路径均可

[logging]
level = "info" # 日志级别: error, warn, info, debug, trace
path = "logs"  # 日志输出文件路径，默认输出到控制台以及文件

[error_exporter]
path = "output/error.log" # 错误日志输出路径
overwrite = true          # 是否覆盖已存在的文件
append = false            # 是否以追加的方式写入文件

[[exporter.csv]]
path = "output/sqllog.csv" # 输出文件路径
overwrite = true           # 是否覆盖已存在的文件
append = false             # 是否以追加的方式写入文件

[[exporter.json]]
path = "output/sqllog.json" # 输出文件路径
overwrite = true            # 是否覆盖已存在的文件
append = false              # 是否以追加的方式写入文件
pretty = true               # 是否美化输出的 JSON 格式
oneline = false             # 是否将每条记录输出为单独一行

[[exporter.sqlite]]
path = "output/sqllog.db" # 输出文件路径
overwrite = true          # 是否覆盖已存在的文件
append = false            # 是否以追加的方式写入表
table = "sqllog"          # 数据库表名

[[exporter.duckdb]]
path = "output/sqllog.duckdb" # 输出文件路径
overwrite = true              # 是否覆盖已存在的文件
append = false                # 是否以追加的方式写入表
table = "sqllog"              # 数据库表名

[[exporter.postgres]]
append = false        # 是否以追加的方式写入表
host = "localhost"    # 数据库主机
port = 5432           # 数据库端口
user = "user"         # 数据库用户
password = "password" # 数据库密码
database = "sqllog"   # 数据库名称
table = "sqllog"      # 数据库表名
schema = "public"     # 数据库模式，默认为 public
